### ISSUE TITLE
add `vak eval` command to command-line interface

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/vak#135]
i.e. to run trained model on a test set

**Comment by NickleDave** [comment]
should use specified dataset to measure 
- [ ] framewise error
- [ ] syllable error rate, AKA normalized edit distance

**Comment by NickleDave** [comment]
Added by #179

**Comment by vivinastase** [comment]
Hi Dave
Could you post an example config file for evaluation? 

Does a dataset need special preparation when used for evaluation?
When trying to use it on a previously prepped dataset I get:
ValueError: split test not found in dataset in csv: <apth to csv file created during prep>

Thanks!

**Comment by NickleDave** [comment]
Hi @vivinastase happy to help.

> Could you post an example config file for evaluation?
You are right that we need to do a better job of documenting how to prepare and run `eval`.

Does this config file from the `tweetynet` paper repository help?
https://github.com/yardencsGitHub/tweetynet/blob/master/article/data/configs/Bengalese_Finches/behavior/bl26lb16/2012-04-20/bl26lb16_eval_042012.toml

> When trying to use it on a previously prepped dataset I get:
ValueError: split test not found in dataset in csv: 

Just to make sure I understand:
* you made a config file with a `TRAIN` section
* and then you ran `vak prep` with that config file
* then you tried to run `eval` with the same config file?

If that's the case, then what you need to do is:
* make a *separate* config file with an `EVAL` section, like the one linked above
* run `vak prep` with that config file, which will create the eval dataset and the .csv representing it, and update the option `csv_path` in the config file with the path to that .csv. The `split` column in that `csv` will have all rows set to `'test'`.
* Then finally run `vak eval new_eval_config.toml` (replacing `new_eval_config.toml` with your)

I know this is a bit confusing, would be happy to hear what you think might be a more intuitive workflow, or how we could document it better

**Comment by vivinastase** [comment]
Thanks for the information and the eval config file, Dave!

What I did was follow the example in the vak doc, and then I wanted to evaluate the predicted annotations. I made a copy of the  gy6or6_predict.toml file which I called gy6or6_eval.toml, in which I replaced the [PREDICT] section with an [EVAL] section, containing the variables I saw in the vak/config/eval.py module. Here is my eval config file:
_____________________________
[PREP]
data_dir = "/home/vivi/Data/Segmentation/TweetyNetData/032312"
output_dir = "/home/vivi/Data/Segmentation/TweetyNetData/032312_predict"
audio_format = "cbin"

[SPECT_PARAMS]
fft_size = 512
step_size = 64


[EVAL]
csv_path = "/home/vivi/Data/Segmentation/TweetyNetData/032312_predict/032312_prep_220309_051349.csv"
checkpoint_path = "/home/vivi/Data/Segmentation/TweetyNetData/032212_train/results/results_220309_051839/TweetyNet/checkpoints/max-val-acc-checkpoint.pt"
output_dir = "/home/vivi/Data/Segmentation/TweetyNetData/032312_predict"
labelmap_path = "/home/vivi/Data/Segmentation/TweetyNetData/032212_train/results/results_220309_051839/labelmap.json"
models = "TweetyNet"
batch_size = 1
num_workers = 4
device = "cuda"
spect_scaler_path = "/home/vivi/Data/Segmentation/TweetyNetData/032212_train/results/results_220309_051839/StandardizeSpect"


[TweetyNet.optimizer]
lr = 0.001
________________________________________________________

Thanks very much for linking the example config file! Looks like I should have dug in a bit more :)

**Comment by vivinastase** [comment]
Because you asked how you could make the process better -- it would be good to have the evaluation part included and described in the vak doc, like the prep and training are, and maybe link some examples of the config files in the doc (https://vak.readthedocs.io/en/latest/reference/config.html#config)

many thanks for your help!

**Comment by NickleDave** [comment]
Perfect, thanks!
