### ISSUE TITLE
vak learncurve fails to create training sets

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#209]
[configs_llb11_llb16.zip](https://github.com/NickleDave/vak/files/4616545/configs_llb11_llb16.zip)

Birds llb11 and llb16 have datasets of ~30,000 seconds each.
Still, after running prep several times with the attached configs the learncurve step does not succeed in creating the training sets.

The training set duration specified are larger than previously (and successfully) attempted.
Can it be that now training sets are prevented from overlap?

**Comment by NickleDave** [comment]
we are working on this now -- closing since there's not a specific code issue here to address
