### ISSUE TITLE
vak predict crashes with no spec transform

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#211]
For some reason, if not using a spectrogram transform (and not pointing to one in the config file) the composite transform (Line 100 in predict.py) has None as the first transform.

The composition sits somewhere upstream but I momentarily overcame by writing
(patching only to be able to follow on the downstream results)
transform.transforms=transform.transforms[1:]

before calling 

    pred_dataset = UnannotatedDataset.from_csv(csv_path=csv_path,
                                               split='predict',
                                               window_size=window_size,
                                               spect_key=spect_key,
                                               timebins_key=timebins_key,
                                               transform=transform,
                                               )

attached is the config
[config-llb16-predict.zip](https://github.com/NickleDave/vak/files/4631859/config-llb16-predict.zip)

**Comment by NickleDave** [comment]
fixed by #221
