### ISSUE TITLE
change predict output to csv

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#212]
Using vak predict to produce not.mat. files for a canary was a problem because the labels are double digit integers and the not.mat. format concatenates them into one long string.

Also, I need to figure out why the onset and offset times were not aligned (given the sampling rate) with the actual times.

The labels themselves are pretty good fits

**Comment by yardencsGitHub** [comment]
I tried to export to formats 'textgrid' and 'yarden' but crashed at predict.py line 199 ..
probably because to_format_kwargs needs another setting

**Comment by NickleDave** [comment]
Editing issue name to "change predict output to csv" and dumping some emails here for context:

> [predictions from .not.mat files] look weird when I visualize them with evsonganaly, the MatLab GUI for annotating song.
> I think it might be that the GUI is actually re-segmenting.
> But the problem is that's the only format we can really get out of vak.predict right now.
> 
> So for me, and for you, I think it's best if I next get it so that vak.predict outputs a csv.
> 
> I am actually thinking it might be best just to have it *only* output a csv, and leave conversion back to some other format to the user.
> The main reason being that it could cause a combinatorial explosion of maintenance problems, if we try to make `vak.predict` responsible for handling all those formats.
> That should be out of scope for vak.
> I think crowsetta provides a tool that helps with the conversion, and we can help users with that tool, but ultimately until there's a team of ninja unicorn developers working on the code I think we should favor limiting the scope wherever possible, and leaving the conversion to users.

**Comment by NickleDave** [comment]
done in #222
