### ISSUE TITLE
Simplify (and speed up) annotation 'unlabeled' checkup when running experiments

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#295]
Currently, a 'learn curve' experiment using Matlab-generated spectrograms starts with loading all these files.
This is a slow step that can be avoided.

**Comment by NickleDave** [comment]
hey @yardencsGitHub thanks for raising this -- actually I just raised the issue in #294

**Comment by NickleDave** [comment]
I know you're busy with other stuff, just wanted to get down my thoughts before I forgot again.

Thank you for helping me spot that issue and walk through a possible fix. Let's continue discussion on that other issue though
