### ISSUE TITLE
Contribution guidelines for `vak`

### ISSUE THREAD

**Issue by Luke-Poeppel** [NickleDave/vak#365]
It would be great to have a `CONTRIBUTING.md` file in the repo––or notes in the `README`––for new contributors to the package. This could contain info on:  
1. Desired commit message formatting
2. Style guide
3. Testing

See [here](https://github.com/cuthbertLab/music21/blob/master/CONTRIBUTING.md) for a nice example.

**Comment by NickleDave** [comment]
You are 100% correct that we should have this.

I am going to add the detail from your comment to the existing issue open about it, just to avoid duplication
