### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by Luke-Poeppel** [NickleDave/vak#367]
**VERSION**: 0.4.0b4

I see [here](https://github.com/NickleDave/vak/pull/351) that a Python version of `'>=3.6.2,<3.9'` is enforced. If you're using conda, this isn't much of an issue –– but if you're only trying to use some of the vak utility functions, this is a bit of a tricky constraint. Changing Python versions is quite a hassle (and I'm not particularly keen to downgrade). If this constraint is only needed because of coverage, I wonder if there's an easier solution?

**Comment by NickleDave** [comment]
I think the upper bounding is just an artifact of when I first switched to `poetry`.

But yes CI takes forever to run already, not sure what will happen if I add a run on 3.9 to GitHub Actions.

Let me try bumping it in a branch, adding a run for 3.9, and seeing what happens.
If it finishes (eventually) I can just go ahead and merge in that change.

**Comment by NickleDave** [comment]
Finished :)

Do you need me to put a new version on PyPI?  
I can just bump the pre-release number.

off-topic but I'd be curious to know which functions you're using as utilities

**Comment by NickleDave** [comment]
closing as fixed by #368
