### ISSUE TITLE
Invalid padding string 'SAME' of pytorch

### ISSUE THREAD

**Issue by zhehao-nkd** [NickleDave/vak#370]
Hi David,

I followed the manual to train the tweetynet model by running:

> vak train gy6or6_train.toml

But I got this error report:

> Traceback (most recent call last):
>   File "/home/chengzh/anaconda3/envs/vak-env/bin/vak", line 8, in <module>
>     sys.exit(main())
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/__main__.py", line 45, in main
>     cli.cli(command=args.command, config_file=args.configfile)
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/cli/cli.py", line 30, in cli
>     COMMAND_FUNCTION_MAP[command](toml_path=config_file)
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/cli/train.py", line 69, in train
>     logger=logger,
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/core/train.py", line 271, in train
>     logger=logger,
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/models/models.py", line 72, in from_model_config_map
>     config=model_config, logger=logger
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/tweetynet/model.py", line 15, in from_config
>     network = TweetyNet(**config['network'])
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/tweetynet/network.py", line 139, in __init__
>     padding=padding
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/tweetynet/network.py", line 21, in __init__
>     super(Conv2dTF, self).__init__(*args, **kwargs)
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 432, in __init__
>     False, _pair(0), groups, bias, padding_mode, **factory_kwargs)
>   File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 92, in __init__
>     padding, valid_padding_strings))
> **ValueError: Invalid padding string 'SAME', should be one of {'valid', 'same'}**

It seems that the torch need lowercase padding string now. How should I solve this problem, maybe by downgrading some packages?

**Comment by NickleDave** [comment]
Hi @zhehao-nkd sorry you're having this issue.

I think this is an issue with `tweetynet` that I'll need to fix.
I can do a bugfix release.

Can you let me know what version of `torch` you're using?
E.g. by running `conda list` when you have your `vak-env` environment activated, and pasting in the results?

I'll want to confirm that that it's a new change to `torch` causing this bug, but probably the fix I will do is just change 'VALID' and 'SAME' to lowercase in the `tweetynet/network.py` module.

If you want a fixed verison sooner you could get a local copy of the tweetynet repo and `pip install -e .` into your conda environment (maybe make a copy of it just to be safe then install into the copied environment) and make that change to lowercase in the module. You'll need to change it in the control flow logic too (e.g. `if padding == 'same'`)

**Comment by zhehao-nkd** [comment]
Hi @NickleDave 

> torch==1.9.0
> torchvision==0.10.0

And I will try to edit the local copy of torch, thanks!

**Comment by NickleDave** [comment]
Thank you @zhehao-nkd ! That helps.

Yes it must be a new change I haven't caught yet.

I should have thought of this before: you should be able to get it work just by installing the earlier version of `torch`.
I have tested with versions up to and including 1.7.1.

There was a bug in the initial release of 1.8.0 so I haven't tested versions higher than that.

I can do that by the end of this coming weekend at the latest.
That fix in `tweetynet` should be relatively simple.

But in the meantime you can test it out by just specifying the earlier version.
E.g. commands for install 1.7.1 with conda would be
```
# conda
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 -c pytorch
```
(from https://pytorch.org/get-started/previous-versions/#v171)

Thank you for catching the bug!
Feel free to reply here if you're still stuck on this issue before I fix it

**Comment by zhehao-nkd** [comment]
Thank you! pytorch==1.7.1 works.
