### ISSUE TITLE
DOC: Cbin Audio Format in Tutorial May Confuse People

### ISSUE THREAD

**Issue by adamfishbein** [NickleDave/vak#456]
The tutorial for automated annotation all worked well but was unfamiliar with the .cbin audio format used.

Could you provide context as to why .cbin format was used and perhaps provide a tutorial with .wav files?

**Comment by NickleDave** [comment]
Good point, thank you @adamfishbein for providing this feedback.

Making notes here. Possible to-do list roughly in order of priority:
- [ ] link to BFSongRepository dataset, to provide context for the .cbin format
- [ ] state that `vak` works with .wav format 
  - even better, link to list of valid formats
  - could that list be dynamically generated, in docs?
  - Currently, valid formats are determined by `vak.constants.VALID_AUDIO_FORMATS`
- [ ] add a separate tutorial that uses .wav
  - could use `birdsong-recognition-dataset` + the annotation for the `tweetynet` paper
  - but would be nice to have one example that is not BFs
