### ISSUE TITLE
pip installing vak fails because pip installs pytorch

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#91]
Perhaps this is a problem in installing torch (https://stackoverflow.com/questions/56859803/modulenotfounderror-no-module-named-tools-nnwrap)
Is it something that needs fixing to allow pip installing vak on a  windows machine?
[err_msg_vak_02112020.txt](https://github.com/NickleDave/vak/files/4208716/err_msg_vak_02112020.txt)

**Comment by NickleDave** [comment]
Hey @yardencsGitHub thanks for posting here in case others run into the issue

I think you are right, it's a problem with installing `torch` directly with `pip`.

Can you try using `conda` instead to install `pytorch` and `torchvision` into a fresh `conda` environment? And the other depenencies too?

Basically the way I install now for development is to make a new environment and then `conda install` all the dependencies listed in the `setup.py` that I know are best installed with conda.

So basically I would do something like
```console
$ conda create -n vak-env python=3.6
$ conda activate vak-env
(vak-env) $ conda install pytorch torchvision -c pytorch
(vak-env) $ conda install attrs dask joblib pandas scipy toml tqdm
(vak-env) $ cd /home/david/repos/coding/vak
(vak-env) $ pip install -e .  # should get other dependencies on pip like crowsetta
```

I made an `environment.yml` file that lists them although I haven't tried using it yet.
It's here:
https://github.com/NickleDave/vak/blob/master/environment.yml

You would use it by running
```
$ conda env create -n vak-env -f environment.yml
```

**Comment by NickleDave** [comment]
Long term we can fix this by making a new version of `vak` for anaconda cloud, so people can just 
`conda install vak -c nickledave`

**Comment by yardencsGitHub** [comment]
Will try.
I’m leaving for 4 days travel tomorrow.
If I don’t make it remotely I’ll do it when back

On Feb 15, 2020, at 7:20 PM, David Nicholson <notifications@github.com> wrote:

Hey @yardencsGitHub <https://github.com/yardencsGitHub> thanks for posting here in case others run into the issue

I think you are right, it's a problem with installing torch directly with pip.

Can you try using conda instead to install pytorch and torchvision into a fresh conda environment? And the other depenencies too?

Basically the way I install now for development is to make a new environment and then conda install all the dependencies listed in the setup.py that I know are best installed with conda.

So basically I would do something like

$ conda create -n vak-env python=3.6
$ conda activate vak-env
(vak-env) $ conda install pytorch torchvision -c pytorch
(vak-env) $ conda install attrs dask joblib pandas scipy toml tqdm
(vak-env) $ cd /home/david/repos/coding/vak
(vak-env) $ pip install -e .  # should get other dependencies on pip like crowsetta
I made an environment.yml file that lists them although I haven't tried using it yet.
It's here:
https://github.com/NickleDave/vak/blob/master/environment.yml <https://github.com/NickleDave/vak/blob/master/environment.yml>
You would use it by running

$ conda env create -n vak-env -f environment.yml

**Comment by yardencsGitHub** [comment]
Hey @NickleDave,
The proposed manual installation works.
